# Generated by Django 3.2.23 on 2023-11-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0002_auto_20231110_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('CAP', 'CAPTAINS QUARTERS'), ('OCD', 'DOUBLE CABIN'), ('OCS', 'SINGLE CABIN'), ('CRW', 'CREW BUNKS')], max_length=3),
        ),
    ]
