# Generated by Django 3.2.23 on 2023-11-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0003_alter_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
