# Generated by Django 3.2.23 on 2023-11-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0005_remove_booking_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('CAP', "CAPTAIN'S QUARTERS"), ('OCD', 'DOUBLE CABIN'), ('OCS', 'SINGLE CABIN'), ('CRW', 'CREW BUNKS')], max_length=3),
        ),
    ]
