# Generated by Django 3.2.23 on 2023-11-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0006_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('CAPQ', "Captain's Quarters"), ('DCBN', 'Double Cabin'), ('SCBN', 'Single Cabin'), ('CRWH', 'Crew Hammocks')], max_length=4),
        ),
    ]
