# Generated by Django 3.2.23 on 2023-11-25 13:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0008_booking_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
