# Generated by Django 3.2.23 on 2023-11-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0011_auto_20231127_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
