# Generated by Django 3.2.23 on 2023-11-29 15:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0013_auto_20231128_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=cloudinary.models.CloudinaryField(default='/media/room_placeholder.jpg', max_length=255, verbose_name='image'),
        ),
    ]
