# Generated by Django 3.2.23 on 2023-11-29 15:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0017_alter_room_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_1',
            field=cloudinary.models.CloudinaryField(default='placeholder1', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_2',
            field=cloudinary.models.CloudinaryField(default='placeholder2', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_3',
            field=cloudinary.models.CloudinaryField(default='placeholder3', max_length=255, verbose_name='image'),
        ),
    ]
