# Generated by Django 3.2.23 on 2023-12-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0019_auto_20231209_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
