# Generated by Django 3.2.23 on 2023-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0020_alter_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image_1_alt',
            field=models.CharField(default='Image description', max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_2_alt',
            field=models.CharField(default='Image description', max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_3_alt',
            field=models.CharField(default='Image description', max_length=500),
        ),
    ]
