# Generated by Django 3.2.23 on 2023-12-09 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0020_auto_20231209_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
