# Generated by Django 3.2.23 on 2023-12-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd_bookings', '0021_auto_20231211_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image_1_alt',
            field=models.CharField(default='Image description', max_length=500, verbose_name='alt text'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image_2_alt',
            field=models.CharField(default='Image description', max_length=500, verbose_name='alt text'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image_3_alt',
            field=models.CharField(default='Image description', max_length=500, verbose_name='alt text'),
        ),
    ]
